# Generated by Django 5.1.2 on 2025-06-03 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_publish_product', 'Can publish product')]},
        ),
    ]
