# Generated by Django 5.1.2 on 2025-06-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('clothes', 'clothes'), ('kitchin', 'kitchin'), ('food', 'food'), ('elctronic', 'elctronic')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='mystore_pro_name_c5f172_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='mystore_pro_categor_69d61c_idx'),
        ),
    ]
